BOARD_SIZE = 6
CONSECUTIVE_STONE_COUNT = 4

BLACK_PLAYER = 1
WHITE_PLAYER = 2
EMPTY = 0

NEW_MODEL = 1
OLD_MODEL = 2

WINNER_BLACK = BLACK_PLAYER
WINNER_WHITE = WHITE_PLAYER
WINNER_DRAW = 3
WINNER_NONE = 4

DRAW_REWARD = -0.0
WIN_REWARD = 1.0
LOSE_REWARD = -1.0

N_PLAYOUT = 400
TEMPERATURE = 1
C_PUCT = 5


OLD_MODEL_FILE = "gomoku_model_old.pth"
NEW_MODEL_FILE = "gomoku_model_new.pth"